### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/bootstrap-margin-grid#1]
- [x] Generate mobile classes.
- [ ] Make some CodePens illustrating each perfectly.
- [ ] See if it's a drop-in replacement (are things coupled to Bootstrap's grid). If it is, add in offsets and all that junk. Otherwise it's just a proof-of-concept.
